### ISSUE TITLE
Нормализация ссылок

### ISSUE THREAD

**Issue by alexshpilkin** [fedor57/alumni-directory#1]
Важное: — ссылки вида `vk.com/blah` и `facebook.com/blah` браузером воспринимаются как относительные и не работают, но набирать `http[s]://` в начале явно будут не все; — сейчас вместо ссылки на контакт/фейсбук можно ввести любую ссылку и даже любой мусор.

Красивости: ссылки надо бы нормализовать: http/https везде; фейсбук любит добавлять в конце всякий трекинговый мусор (никакие параметры в profile.php, кроме id, не нужны; остальным страницам вообще никакие параметры не нужны).

Сложное: хорошо бы удостовериться, что ссылка на профиль действительно ведёт на профиль, а не на что-нибудь другое внутри домена социалочки (действия по `GET` выполнять нельзя, так что уязвимости быть не должно, но мы же все знаем, как хорошо это все соблюдают?..)

**Comment by kostichek** [comment]
Предлагаю также маскировать ссылку на домашнюю страницу, например HP, а также ограничить вывод полей Город, Вуз/Работа по длине, по наведении мыши - полное название. Также ВК, FB итд лучше стандартными иконками. В итоге получим список а-ля табличной верстки, который для списка наиболее воспринимаемый.

**Comment by mxposed** [comment]
Ссылки теперь можно вводить только с http/https, имеющиеся в базе были нормализованы, вроде)

**Comment by alexshpilkin** [comment]
@mxposed Оно прямо требует http в начале? Странно людям запрещать писать просто `vk.com/blah`, они в браузере привыкли так делать.

FB и ВК можно всегда переделывать в https, но это уже виньеточка.

**Comment by mxposed** [comment]
@alex-shpilkin мне кажется, люди в основном копируют эти ссылки, а браузеры копируют с протоколом. Как думаешь, в текущем виде оно ещё требует переделки?
