### ISSUE TITLE
Отсутствуют профили классов

### ISSUE THREAD

**Issue by alexshpilkin** [fedor57/alumni-directory#13]
Профили классов (поле `profile`) в базе не заполнены, потому что я давным-давно налажал и забыл их экспортировать из базы sch57.ru. Я поправил экспорт, и [по старой ссылке][1] сейчас у всех классов классов указан профиль (в поле `speciality`, потому что _profile_ по словарю значит не это, но я и в _speciality_ не уверен).

[1]: http://sch57.ru/people/alumni/data.json

**Comment by fedor57** [comment]
Коль, я собирался руками зафигачить, но что-то там многовато будет. Может ты отпарсишь через jq из json тип класса и джоин-апдейтом заапдейтишь? Спасибо!

**Comment by alexshpilkin** [comment]
@fedor57 Да и я могу через jq отпарсить, вы только опишите, в каком виде оно в итоге должно оказаться. (Пару слов про то, как должен выглядить нужный UPDATE, или что там в итоге должно быть.)

**Comment by fedor57** [comment]
Готово, закрываем!
