### ISSUE TITLE
Откат собственных изменений

### ISSUE THREAD

**Issue by alexshpilkin** [fedor57/alumni-directory#2]
Сабж. Хорошо бы иметь возможность без шума и подтверждений откатывать собственные изменения — хотя бы недавние, поверх которых никто больше ничего не сделал. Включая создание фантомных выпускников по ошибке (удалить из интерфейса нельзя; мы же не хотим это всё решать через суппорт?). Можно было бы даже изменять, а не откатывать, но откатывать легче для интерфейса и реализации.

via: Посицельский, Равинская

**Comment by fedor57** [comment]
Сделали логику "удаления правок", после которого правка полностью скрывается. Если не было неанонимных голосов за, то правку можно удалить:
а) автором
б) анонимную правку двумя голосами авторизованных против

Удаление лишних выпускников предлагаю делать через саппорт, это минорный кейс.
