### ISSUE TITLE
Умершие выпускники

### ISSUE THREAD

**Issue by kostichek** [fedor57/alumni-directory#3]
Предлагаю помечать покинувших нас и блокировать действия с ними. В общем списке отображение нет смысла менять, ибо мемориал иначе получится. И, наверное, надо сделать кнопку репорта - "выпускник покинул нас", где-нибудь не на виду.

**Comment by fedor57** [comment]
Решили добавить поле "год смерти" и отображать в списке в виде UNICODE+2020 и года. Рядом может быть ссылка на внешнюю страницу с рассказом или некрологом.

† 1999

Блокировку отдельных выпускников сделаем отдельно как административный флажок, который админы могут поставить вручную. Автоматом ставить не будем, это далеко не всегда нужно.

**Comment by fedor57** [comment]
Нужно пофиксить, добавить пробел перед крестиком
