### ISSUE TITLE
Доработки статусов

### ISSUE THREAD

**Issue by ghost** [fedor57/alumni-directory#8]
В текущем виде статусы выставляются как-то так, поэтому тут тоже нужен порядок и правила:

__Удалённый статус__
1. Если ты за логином, добавила факт, и голосуешь за его удаление: он переход в статус «удалённый»
2. Если факт добавлен анонимом, а за него есть два не-анонимных голоса «против» и 0 голосов «за», то он переходит в статус «удалённый»
3. Если ты за логином и голосуешь «против» факта на своей странице, он переходит в статус «удалённый» — без всяких, просто.

Факты с удалённым статусом не видны нигде.

Выход из удалённого статуса возможен, если факт был помечен удалённым по причине 1 или 2, и кто-то добавил точно такой же факт. В этом случае, факт переходит из статуса «удалённый» в какой-то другой, и вернуть его в «удалённый» может только хозяин страницы.

__Скрытый статус__
1. Виден за кликом

__Неуверенный статус__
1. Отображается серым

__Уверенный статус__
1. Отображается обычным шрифтом

__Рассчёт статуса__
Статусы «скрытый», «неуверенный», «уверенный» рассчитывают так: добавление факта и голос «за» него считаются положительными голосами, голос «против» и голос «за удаление» считаются отрицательными. Если голосует хозяйка страницы, к которой прицеплен факт, то голос умножается на 10. Если голосует аноним, то голос делится на 10.
После подсчёта голосов для каждого типа значения (город, ВУЗ и т. п.) выбирается факт с максимальным весом. Этот факт получает статус «уверенный», остальные факты с положительным весом — статус «неуверенный», остальные с отрицательным весом — статус «скрытый».

**Comment by fedor57** [comment]
Вопрос 1:
- "удаление" - это способ скрыть треш с глаз, чтобы на повестке дня не стоял вопрос "правильный он или нет". Если кто-то добавил факт снова, по-идее, можно просто зарегистрировать голос ЗА, потом пересчитать статус по старым правилам без учета того, что он был удален, и тогда он может перестать быть удаленным (кроме случая, когда ПРОТИВ проголосовал автор, например). Не стоит ли сделать статусы только функцией голосов, но не предыдущего статуса? Из твоего описания не очевидно, что это именно так

**Comment by fedor57** [comment]
Вопрос 2:
- не стоит ли неуверенным считать факт, у которого вес положительный, но меньше 0.9? Кажется, что это спровоцирует авторизованных пользователей подтвердить факты, чтобы они были уверенными, тогда мы соберем больше информации.

**Comment by ghost** [comment]
Вопрос 2: ты имеешь в виду «скрытый»? Или ты имеешь в виду не давать факту от анонима с весом 0.1 быть «уверенным»?

**Comment by ghost** [comment]
Вопрос 1: да, статус это функция только от голосов, но с некоторыми дополнительными условиями, правда. Но порядок голосов не влияет, или предыдущий статус тоже не влияет.

Условия все касаются статуса «удалённый» и они такие:
1. Если за факт есть только голос «за удаление» от автора факта
2. Если за факт есть голос «за удаление» от хозяйки страницы
3. Если за факт есть > 1 голоса «против» от залогинов и 0 голосов «за» от залогинов (или и от анонимов тоже?)

**Comment by ghost** [comment]
В финальной схеме немного поменяли логику расчёта неудалённых статусов.

__Рассчёт статуса__
Статусы «скрытый», «неуверенный», «уверенный» рассчитывают так: добавление факта и голос «за» него считаются положительными голосами, голос «против» и голос «за удаление» считаются отрицательными. Если голосует хозяйка страницы, к которой прицеплен факт, то голос умножается на 10. Если голосует аноним, то голос делится на 10.
Факт с весом > 0.9 получает статус «уверенный», факт с положительным весом — статус «неуверенный», остальные с отрицательным весом — статус «скрытый».
